WIP: Updating the resources for the website
vmware-samples/vcenter-event-broker-appliance pull request #195
Opened 2020-08-14 15:33 UTC by pksrc

## Summary

Please describe your changes and what you plan to introduce as part of this pull request submission. If it fixes a bug or resolves a feature request, be sure to link to the issue numbers following the template below.

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [x] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commmits related to your change
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Testing Verification

* Tested on https://veba.pdotk.com/resources 

## Additional Information

CNAME will be changed during the final rebase after LGTM from reviewers

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

2020-09-01 19:40 UTC, rguske commented
Hi @pksrc, I'd assume that @embano1 will ask you to `squash` into just one final `commit`. If you don't mind, could you please do this?
Thanks buddy

2020-10-18 04:56 UTC, pksrc commented
Updated with the latest Resources and the featured functions on the homepage has also been updated. 
Can be tested at https://veba.pdotk.com/resources & https://veba.pdotk.com

cc @rguske @vladi-velikov @kremerpatrick @embano1 @lamw - please verify content

All Commits will be squashed and the CNAME change reverted after a LGTM.

2020-10-18 21:47 UTC, kremerpatrick commented
LGTM except the language for the Infrastructure Self Service + Automatic Remediations under featured functions. 'Additionally, enables you to handle certain crises are automatically to increase your operational efficiency' I'm thinking the stray 'are' needs to be removed?

2020-10-23 17:12 UTC, rguske commented
@pksrc - you can delete the link to the `HA restart function` post under the `Other references` section, because it's already mentioned under `Featured References`. Thanks

2020-10-23 19:11 UTC, rguske commented
Good catch @kremerpatrick - I fixed this in behalf of @pksrc while working on other updates and additions. Thanks

2020-12-10 19:36 UTC, embano1 commented
Note, in order to get these into the 0.5 release these changes (PR) must be made against the release branch.

2020-12-11 08:19 UTC, rguske commented on docs/_functions/sample2.md
> + Deploy Function: https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/examples/powercli/ha-restarted-vms
The link has to reference to .../tree/`master`/examples...

2020-12-11 08:31 UTC, rguske requested changes
This little issue has to be fixed (commented): docs/_functions/sample2.md

2020-12-11 14:25 UTC, merged