Adding VEBA Evolutions to the website
vmware-samples/vcenter-event-broker-appliance pull request #530
Opened 2021-08-02 01:58 UTC by pksrc

## Summary

Please describe your changes and what you plan to introduce as part of this pull request submission. If it fixes a bug or resolves a feature request, be sure to link to the issue numbers following the template below.

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [x] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [x] Please include any relevant screenshots and/or output as part of your testing
- [x] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

List of Issues closed or resolved by this PR. Add multiple `Closes` keyword followed by the issue number (e.g. Closes #ISSUE-NUMBER)

Closes #483 

## Testing Verification

![2021-08-01_18-52-36](https://user-images.githubusercontent.com/30903187/127794497-8b43ca9e-064c-4a9a-a3ac-008ccebe6de2.png)

## Additional Information

* Any other details you wish to include or mention

If you have any questions/comments, feel free to reach out to team on Slack [#vcenter-event-broker-appliance](https://vmwarecode.slack.com/archives/CQLT9B5AA)

Thank you from the VEBA Team! 🥳

2021-08-02 09:41 UTC, embano1 commented
AWESOME WORK!

2021-08-04 12:21 UTC, lamw commented on docs/site/evolutions.md
> +    - Introduced VEBA v0.1.0 with OpenFaaS as the default Event Processor​ and vCenter as the Event Provided
```suggestion
    - Introduced VEBA v0.1.0 with OpenFaaS as the default Event Processor​ and vCenter as the Event Provider
```

2021-08-04 12:22 UTC, lamw commented on docs/site/evolutions.md
> +    - Added support for AWS EventBridge as the Event Processor
```suggestion
    - Added support for AWS EventBridge as an Event Processor
```

2021-08-04 12:23 UTC, lamw commented on docs/site/evolutions.md
> +  id: vzerofive
```suggestion
  id: vzerosix
```

2021-08-04 12:25 UTC, lamw commented on docs/site/evolutions.md
> +    - vSphere UI integration (h5 Client Plugin)​
```suggestion
    - vSphere UI integration (H5 Client Plugin)​
```

2021-08-04 12:26 UTC, lamw requested changes
Couple of minor changes.

I noticed in the screenshot for items located on the right, the text is aligned `right`, would it read better to have text aligned `left` next to bullets?

2021-08-05 04:34 UTC, pksrc commented
preview of the latest changes as requested
![image](https://user-images.githubusercontent.com/30903187/128291381-4b4731e2-6216-41b7-8b72-0adbdaf2046c.png)

2021-08-06 16:47 UTC, lamw approved these changes
🥳 

Awesome work @pksrc

2021-08-06 16:47 UTC, merged