Add deployment methods section to welcome page
vmware-samples/vcenter-event-broker-appliance pull request #559
Opened 2021-08-30 09:16 UTC by rguske

Signed-off-by: Robert Guske <rguske@vmware.com>

## Summary

This PR will add a new section to the website (Home) which highlights the two supported deployment methods for VEBA.

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [x] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [x] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [x] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [x] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [x] Please include any relevant screenshots and/or output as part of your testing
- [x] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

## Resolved Issues

Closes: #517

## Testing Verification

* Successfully verified website adjustments locally

![image](https://user-images.githubusercontent.com/31652019/131316499-1054d0f0-bdc7-44e9-86ce-47cd8b0beaab.png)

## Additional Information

N/A

2021-09-03 03:02 UTC, pksrc commented
Design LGTM, One suggestion that I have is to maybe use this section with a smaller version of the images. I say that because I believe that section does not have super strong CTAs and could be repurposed for this content. 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/30903187/131944169-22e0aa4a-b4d5-418f-8936-ffcb97963d82.png">

2021-09-03 04:51 UTC, rguske commented
> Design LGTM, One suggestion that I have is to maybe use this section with a smaller version of the images. I say that because I believe that section does not have super strong CTAs and could be repurposed for this content. 
> 
> <img width="584" alt="image" src="https://user-images.githubusercontent.com/30903187/131944169-22e0aa4a-b4d5-418f-8936-ffcb97963d82.png">
> 
> 

Thanks for your review PK. Code-wise it's fine?
I've chosen this way of highlighting the deployment options, because this topic came up several times in customer discussions and IMO our supported options should be very clear (highlighted). Also, it fits very well for the mobile version of the website which is very important IMO too.

2021-09-05 13:40 UTC, rguske commented
@lamw @embano1 @pksrc 

Here are further alternatives according to what we've discussed on Friday. Please comment.

1. w/ section header
![image](https://user-images.githubusercontent.com/31652019/132128998-619c1810-6dfb-47a3-817e-5ffaeb2bdcc0.png)

2. w/o section header
![image](https://user-images.githubusercontent.com/31652019/132129018-75db9df4-e5d0-45a6-94b4-49d1b312a50d.png)

3. In grey w/o icons
![image](https://user-images.githubusercontent.com/31652019/132128843-c1feabf0-5ed0-4092-a8da-32f538f69702.png)

2021-09-05 20:17 UTC, pksrc commented
I like the last one - Can you remove the first two items - Explore the documentation and Get started quickly. And add a title that indicates that this section is for deployment types?

2021-09-05 21:38 UTC, vladi-velikov commented
Like @pksrc I prefer 3. too.
Just IMO we should use either a grey area with no title or a title without a grey area. Otherwise it becomes confusing to me what kind of info this is and it's relation to the other sections (e.g. sibling or not a sibling).

2021-09-06 06:01 UTC, rguske commented
Thanks a lot for your feedback @pksrc and @vladi-velikov 👍🏻 
I'd like to keep the icons as well and agree with your suggestions.

![image](https://user-images.githubusercontent.com/31652019/132167953-95224abe-d21a-470e-8009-f6f772f4f735.png)

2021-09-06 09:10 UTC, embano1 commented
> I'd like to keep the icons as well

I also prefer option three (as the other gentlemen), but that option did not have the icons and IMHO it looks better w/out icons.

2021-09-06 11:36 UTC, rguske commented
Happy?

![image](https://user-images.githubusercontent.com/31652019/132211596-cb02068f-431b-4036-a6bc-65f3105c9f60.png)

2021-09-06 12:01 UTC, embano1 commented
What about option "3 In grey w/o icons" you showed above? I'm not sure featuring deployment methods on the main page is a key selling item?

2021-09-08 11:08 UTC, rguske commented
@lamw @embano1
Heres now the final version for this part based on what we've decided yesterday. I'm happy with it 👍🏻 
@pksrc Your final review would be great. Thanks.

![image](https://user-images.githubusercontent.com/31652019/132498587-e5f0ba96-0659-4f72-8820-0b61add43901.png)

2021-09-08 12:07 UTC, embano1 commented
Can you please squash the commits?

2021-09-08 15:00 UTC, embano1 commented on docs/index.html
> +    content: Deploy VEBA directly onto vSphere by using the ready-to-run appliance (OVA) method.
```suggestion
    content: Deploy VEBA directly onto vSphere by using the ready-to-run appliance (OVA.
```

2021-09-08 15:01 UTC, embano1 requested changes
Thx, one nit.

2021-09-08 15:06 UTC, embano1 approved these changes
THX!

2021-09-08 15:10 UTC, merged