Add PowerShell SMS example using Twillo
vmware-samples/vcenter-event-broker-appliance pull request #584
Opened 2021-09-10 16:39 UTC by lamw

Closes #582 
Signed-off-by: William Lam <wlam@vmware.com>

## Summary

SMS message sent via Twillo when a VM snapshot is created 

![screenshot-1](https://user-images.githubusercontent.com/602199/132885490-39696f5b-ef52-4389-84d0-2694195a2f64.png)

## Pull Request Checklist
🚨 Please review the [guidelines for contributing](https://vmweventbroker.io/community) to this repository.

- [ ] Please ensure that you are making a pull request against the **Development** branch
- [ ] Please use the `WIP` keyword in the title of your PR if you are not ready for review
- [ ] Please ensure that you have opened a Github Issue if you are resolving/fixing a problem
- [ ] Please ensure that you have [signed](https://help.github.com/en/github/authenticating-to-github/signing-commits) all commits and that you have [squashed](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) all relevant commits related to your change
- [ ] Please make sure that you have tested your change locally by successfully [building and deploying the VMware Event Broker Appliance](https://vmweventbroker.io/kb/contribute-appliance) and/or [building and deploying VMware Event Router](https://vmweventbroker.io/kb/contribute-eventrouter)
- [ ] Please include any relevant screenshots and/or output as part of your testing
- [ ] Please include any documentation updates that is applicable for your changes

## Change Type

What types of changes does your code introduce to the VMware Event Broker Appliance?

_Put an `x` in all boxes that apply_

Please check the type of change your PR introduces:
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation changes
- [ ] Other (please describe):

2021-09-14 19:36 UTC, embano1 requested changes
Minor changes requested

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/README.md
> +Update the `sms_secret.json` file with you Twillo credentials and configurations and then create the kubernetes secret which can then be accessed from within the function by using the environment var
```suggestion
Update the `sms_secret.json` file with your Twillo credentials and configuration and then create the kubernetes secret which can then be accessed from within the function by using the environment variable named `SMS_SECRET`.
```

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/README.md
> +Edit the `function.yaml` file with the name of the container image from Step 1 if you made any changes. If not, the default VMware container image will suffice. By default, the function deployment wi
```suggestion
Edit the `function.yaml` file with the name of the container image from Step 1 if you made any changes. If not, the default VMware container image will suffice. By default, the function deployment will filter on the `TaskEvent` vCenter Server Event and VM snapshot creation task. For more details on identifying a specific task descriptionId from a TaskEvent, please [see this blog post](https://williamlam.com/2019/02/creating-vcenter-alarms-based-on-task-events-such-as-folder-creation.html) for more details. If you wish to change this, update the `subject` field within `function.yaml` to the desired event type.
```

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/README.md
> +
Remove empty line

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/README.md
> +For testing purposes, the `function.yaml` contains the following annotations, which will ensure the Knative Service Pod will always run **exactly** one instance for debugging purposes. Functions depl
```suggestion
For testing purposes, the `function.yaml` contains the following annotations, which will ensure the Knative Service Pod will always run **exactly** one instance for debugging purposes. Functions deployed through the VMware Event Broker Appliance UI defaults to scale to 0, which means the pods will only run when it is triggered by an vCenter Event.
```

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/function.yaml
> +      type: com.vmware.event.router/event
Feel free to drop

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/handler.ps1
> +   if($cloudEventData.Info.DescriptionId -eq "VirtualMachine.createSnapshot") {
Perhaps an else or default clause would be neat to log that it skipped this TaskEvent.

2021-09-14 19:36 UTC, embano1 commented on examples/knative/powershell/kn-ps-twillio-sms/handler.ps1
> +      if($StatusCode -eq "201") {
Else clause with other status code would be neat to log

2021-09-14 20:12 UTC, lamw commented
All feedback addressed

2021-09-15 07:34 UTC, embano1 approved these changes
LGTM

2021-09-16 20:51 UTC, embano1 approved these changes
LGTM

2021-09-16 20:51 UTC, merged